"""initial schema

Revision ID: a12e28fef65b
Revises: 
Create Date: 2026-09-11 00:27:18.746804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a12e28fef65b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processed_operations',
    sa.Column('operation_id', sa.String(length=36), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('operation_id')
    )
    op.create_table('facility_services',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('facility_id', sa.String(length=36), nullable=False),
    sa.Column('service_name', sa.String(length=128), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facility_id', 'service_name', name='uq_facility_service_name')
    )
    op.create_table('role_assignments',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('unassigned', 'worker', 'facility', 'admin', name='ck_role_assignments_role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('facility_id', sa.String(length=36), nullable=True),
    sa.CheckConstraint("(role = 'facility' AND facility_id IS NOT NULL) OR (role != 'facility' AND facility_id IS NULL)", name='ck_role_assignments_facility_role_requires_facility_id'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('unassigned', 'worker', 'facility', 'admin', name='ck_users_role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('facility_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(role = 'facility' AND facility_id IS NOT NULL) OR (role != 'facility' AND facility_id IS NULL)", name='ck_users_facility_role_requires_facility_id'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_table('patients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('approximate_age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('village', sa.String(length=255), nullable=True),
    sa.Column('registered_by', sa.String(length=36), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('approximate_age IS NULL OR (approximate_age >= 0 AND approximate_age <= 130)', name='ck_patients_approx_age_range'),
    sa.CheckConstraint('date_of_birth IS NOT NULL OR approximate_age IS NOT NULL', name='ck_patients_dob_or_approx_age'),
    sa.ForeignKeyConstraint(['registered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('chief_complaint', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Enum('local_care', 'referral', name='ck_assessments_recommendation', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referrals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('assigned_facility_id', sa.String(length=36), nullable=False),
    sa.Column('required_service', sa.String(length=128), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('ASSIGNED', 'CONFIRMED', 'ARRIVED', 'CONSULTED', 'FOLLOW_UP', 'CLOSED', 'DECLINED', 'NO_SHOW', 'CANCELLED', name='ck_referrals_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('closure_reason', sa.String(length=64), nullable=True),
    sa.Column('referred_from_referral_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('arrived_at', sa.DateTime(), nullable=True),
    sa.Column('consulted_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['assigned_facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['referred_from_referral_id'], ['referrals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consultation_outcomes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('referral_id', sa.String(length=36), nullable=False),
    sa.Column('recorded_by', sa.String(length=36), nullable=False),
    sa.Column('diagnosis_summary', sa.Text(), nullable=False),
    sa.Column('treatment_given', sa.Text(), nullable=True),
    sa.Column('medicines', sa.Text(), nullable=True),
    sa.Column('diagnostics_ordered', sa.Text(), nullable=True),
    sa.Column('requires_followup', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_id')
    )
    op.create_table('follow_ups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('referral_id', sa.String(length=36), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', 'missed', name='ck_follow_ups_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_id')
    )
    op.create_table('referral_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('referral_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.Enum('REFERRAL_ASSIGNED', 'REFERRAL_CONFIRMED', 'REFERRAL_DECLINED', 'REFERRAL_CANCELLED', 'PATIENT_ARRIVED', 'NO_SHOW_RECORDED', 'CONSULTATION_RECORDED', 'FOLLOW_UP_SCHEDULED', 'REFERRAL_CLOSED', 'FOLLOW_UP_COMPLETED', name='ck_referral_events_event_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('from_status', sa.Enum('ASSIGNED', 'CONFIRMED', 'ARRIVED', 'CONSULTED', 'FOLLOW_UP', 'CLOSED', 'DECLINED', 'NO_SHOW', 'CANCELLED', name='ck_referral_events_from_status', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('to_status', sa.Enum('ASSIGNED', 'CONFIRMED', 'ARRIVED', 'CONSULTED', 'FOLLOW_UP', 'CLOSED', 'DECLINED', 'NO_SHOW', 'CANCELLED', name='ck_referral_events_to_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=False),
    sa.Column('actor_role', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referral_events')
    op.drop_table('follow_ups')
    op.drop_table('consultation_outcomes')
    op.drop_table('referrals')
    op.drop_table('assessments')
    op.drop_table('patients')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_table('users')
    op.drop_table('role_assignments')
    op.drop_table('facility_services')
    op.drop_table('processed_operations')
    op.drop_table('facilities')
    # ### end Alembic commands ###
